Document: hiddenmarkov
Title: Debian hiddenmarkov Manual
Author: <insert document author here>
Abstract: This manual describes what hiddenmarkov is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hiddenmarkov/hiddenmarkov.sgml.gz

Format: postscript
Files: /usr/share/doc/hiddenmarkov/hiddenmarkov.ps.gz

Format: text
Files: /usr/share/doc/hiddenmarkov/hiddenmarkov.text.gz

Format: HTML
Index: /usr/share/doc/hiddenmarkov/html/index.html
Files: /usr/share/doc/hiddenmarkov/html/*.html
